apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: rivulet
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: rivulet
    app.kubernetes.io/component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: rivulet
        app.kubernetes.io/component: frontend
      annotations:
        rivulet.io/nginx-config-checksum: "3ff933dbb645"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: ghcr.io/athithya-sakthivel/rivulet-frontend:183c4ea
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_URL
              value: "http://api-gateway.rivulet.svc.cluster.local:8080"
            - name: NGINX_ENVSUBST_FILTER
              value: "^BACKEND_URL$"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: nginx-templates
              mountPath: /etc/nginx/templates
              readOnly: true
            - name: nginx-conf-d
              mountPath: /etc/nginx/conf.d
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: tmp
              mountPath: /tmp
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: nginx-templates
          configMap:
            name: frontend-nginx-config
            defaultMode: 0444
            items:
              - key: default.conf.template
                path: default.conf.template
        - name: nginx-conf-d
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
